from __future__ import annotations

from typing import Any, Protocol

from argus.contracts.models import CollectionRecord, Evidence, Observation, Snapshot
from argus.recipes.models import SiteRecipe


class Repository(Protocol):
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...
    async def health(self) -> dict[str, object]: ...
    async def create_collection(self, record: CollectionRecord) -> None: ...
    async def get_collection(self, collection_id: str) -> CollectionRecord | None: ...
    async def list_recoverable_collections(self) -> list[CollectionRecord]: ...
    async def update_collection(self, record: CollectionRecord) -> None: ...
    async def add_observation(self, observation: Observation) -> None: ...
    async def list_observations(self, collection_id: str) -> list[Observation]: ...
    async def add_evidence(self, evidence: Evidence, collection_id: str) -> None: ...
    async def list_evidence(self, collection_id: str) -> list[Evidence]: ...
    async def add_snapshot(self, snapshot: Snapshot) -> None: ...
    async def latest_snapshot(self, source_url: str) -> Snapshot | None: ...
    async def save_recipe(self, recipe: SiteRecipe) -> None: ...
    async def get_recipe(self, domain: str, goal: str) -> SiteRecipe | None: ...


class WorkerQueueRepository(Repository, Protocol):
    async def register_worker(
        self,
        worker_id: str,
        *,
        metadata: dict[str, Any] | None = None,
    ) -> None: ...

    async def heartbeat_worker(self, worker_id: str) -> bool: ...
    async def unregister_worker(self, worker_id: str) -> None: ...
    async def active_worker_count(self, *, max_age_seconds: float) -> int: ...

    async def claim_next_collection(
        self,
        worker_id: str,
        *,
        lease_seconds: float,
    ) -> str | None: ...

    async def renew_collection_lease(
        self,
        collection_id: str,
        worker_id: str,
        *,
        lease_seconds: float,
    ) -> bool: ...

    async def release_collection_lease(
        self,
        collection_id: str,
        worker_id: str,
    ) -> None: ...
